name: Setup Dependancies

runs:
  using: "composite"
  steps:
    - name: Import GPG key 
      shell: bash
      run: |
        echo -n "$GPG_SIGNING_KEY" | base64 --decode > private.key 
        gpg --batch --import private.key
